# -*- mode: python -*-
a = Analysis(['.\\manage.py'],
             pathex=['.'],
             hiddenimports=[
				'django.test',
				'django.utils.six',
				'ConfigParser',
				'copy_reg',
				'cookielib',
				'Cookie',
				'htmlentitydefs',
				'HTMLParser',
				'httplib',
				'email',
				'email.mime',
				'BaseHTTPServer',
				'CGIHTTPServer',
				'SimpleHTTPServer',
				'cPickle',
				'Queue',
				'repr',
				'SocketServer',
				'thread',
				'markupbase', # FROM HTMLParser!!
				'django.contrib.sessions.serializers',
				'django.templatetags.cache',
				'django.templatetags.future',
				'django.templatetags.i18n',
				'django.templatetags.l10n',
				'django.templatetags.static',
				'django.templatetags.tz',
			 ],
             hookspath=None,
             runtime_hooks=None)
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='thief.exe',
          debug=False,
          strip=None,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name='thief')
